# Site settings
title: Gaussian Processor
header-img: img/home-bg.jpg
email: kslauria@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I want to do linear algebra using my computer. But first, I'll have
  to build it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kshitijl.github.io"
github_username:  kshitijl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
